eleng/cart/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('delete/<int:product_id>/', views.cart_delete, name='cart_delete'),
]

eleng/eleng/urls.py
from django.contrib import admin
from django.urls import path, include
from eleng import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from project.sitemaps import NewsSitemap, CategorySitemap, ProductSitemap, StaticViewSitemap

sitemaps = {
    'products': ProductSitemap,
    'categories': CategorySitemap,
    'news': NewsSitemap,
    'static': StaticViewSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('catalog/', include('catalog.urls')),
    path('news/', include('news.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

# В режиме отладки добавляем новый маршрут. Префикс MEDIA_URL свяжем с маршрутом document_root, который указан в корневом каталоге media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eleng/users/urls.py
from django.urls import path
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(
                        template_name='users/password_change_done.html'),
                        name='password_change_done'),
    path('password-reset/', PasswordResetView.as_view(
                        template_name='users/password_reset_form.html', 
                        email_template_name="users/password_reset_email.html",
                        success_url=reverse_lazy("users:password_reset_done")), name="password_reset"),
    path('password-reset/done/', PasswordResetDoneView.as_view(
                        template_name='users/password_reset_done.html'),
                        name="password_reset_done"),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
                        template_name="users/password_reset_confirm.html",
                        success_url=reverse_lazy("users:password_reset_complete")),
                        name="password_reset_confirm"),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
                        template_name="users/password_reset_complete.html"), name="password_reset_complete"),
    
    path('invalid_verify/', TemplateView.as_view(template_name='users/invalid_verify.html'), name='invalid_verify'),
    path('verify_email/<uidb64>/<token>/', views.EmailVerify.as_view(), name='verify_email'),
    path('confirm_email/', TemplateView.as_view(template_name='users/confirm_email.html'), name='confirm_email'),

    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
]

eleng/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from social_django.models import UserSocialAuth
from django.urls import reverse


class User(AbstractUser):
    avatar = models.ImageField(upload_to="users/%Y", default="default/avatar_icon.png", blank=True, null=True, verbose_name="Аватар")
    email_verify = models.BooleanField(default=False)
    

    class Meta:
        db_table = 'auth_user'
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def save(self, *args, **kwargs):
        # Проверка, связан ли этот пользователь с аккаунтом социальной сети
        if UserSocialAuth.objects.filter(user=self).exists():
            self.email_verify = True
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('users:profile')

eleng/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.forms import widgets


class CustomClearableFileInput(forms.ClearableFileInput):
    template_name = 'users/custom_clearable_file_input.html'  # Указываем кастомный шаблон


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={"class": 'form-input', 'placeholder': 'Введите логин или e-mail'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={"class": 'form-input', 'placeholder': 'Введите пароль'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']
        



class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={"class": 'form-input'}))
    password1 = forms.CharField(label='Пароль',  widget=forms.PasswordInput(attrs={"class": 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля',  widget=forms.PasswordInput(attrs={"class": 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name' : 'Фамилия',
        }
        widgets = {
            'email': forms.TextInput(attrs={"class": 'form-input'}),
            'first_name': forms.TextInput(attrs={"class": 'form-input'}),
            'last_name' : forms.TextInput(attrs={"class": 'form-input'}),
        }

    # def clean_password2(self):
    #     """Валидатор совпадения введеных паролей для ф-ий представлений"""
    #     cd = self.cleaned_data
    #     if cd['password1'] != cd['password2']:
    #         raise forms.ValidationError("Пароли не совпадают!")
    #     return cd['password1']
    

    def clean_email(self):
        """Валидация на уникальность email"""
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={"class": 'form-input'}))
    email = forms.CharField(disabled=True, required=False, label='E-mail', widget=forms.TextInput(attrs={"class": 'form-input'}))


    class Meta:
        model = get_user_model()
        fields = ['avatar', 'username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={"class": 'form-input'}),
            'last_name' : forms.TextInput(attrs={"class": 'form-input'}),
            'avatar': CustomClearableFileInput(),
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

eleng/users/views.py
from django.core.exceptions import ValidationError
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator as token_generator
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.utils.http import urlsafe_base64_decode
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import CreateView, UpdateView



from .forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm
from .mixins import UserIsNotAuthenticated
from .utils import send_email_for_verify
from django.contrib.sites.shortcuts import get_current_site
from .tasks import send_email_for_verify_task


User = get_user_model()


class EmailVerify(View):
    """Представление, обрабатывает подтверждение e-mail"""

    def get(self, request, uidb64, token):
        # получаем нашего юзера передав уникальный идентификатор
        user = self.get_user(uidb64)

        # пользователь получен и токен у нас корректен
        if user is not None and token_generator.check_token(user, token):
            user.email_verify = True
            user.save()
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            login(request, user)
            return redirect('home')
        return redirect('users:invalid_verify')
    
    @staticmethod
    def get_user(uidb64):
        """
        Эта ф-я получает из uidb64 юзера, если не найден в БД, то возвращает None
        """
        try:
            # urlsafe_base64_decode() decodes to bytestring
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except (
            TypeError,
            ValueError,
            OverflowError,
            User.DoesNotExist,
            ValidationError,
        ):
            user = None
        return user


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': "Авторизация"}

    def form_valid(self, form):
        user = form.get_user()

        # Проверяем, верифицирована ли почта у пользователя
        if not user.email_verify:
            messages.error(self.request, 'Ваша электронная почта не подтверждена. Пожалуйста, проверьте вашу почту.')
            return redirect('users:login')

        # Если почта верифицирована, продолжаем стандартный процесс входа
        return super().form_valid(form)



class RegisterUser(UserIsNotAuthenticated, CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': "Регистрация"}
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        # Сохранение пользователя
        user = form.save()
        
        # Отправка письма с подтверждением
        # send_email_for_verify(self.request, user)

        # ----------- версия с CELERY
        current_site = get_current_site(self.request)
        # в delay() нельзя передавать объекты
        send_email_for_verify_task.delay(current_site.domain, user.id)


        return redirect('users:confirm_email')
    

class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': "Профиль пользователя"}

    # перенаправления после успешного изменения данных о пользователя
    def get_success_url(self):
        return reverse_lazy('users:profile')
    
    # Отбираем ту запись, которую будем редактировать и отображать
    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"

eleng/users/templates/users/confirm_email.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2 class="users-h2" style="text-align: center;">Пожалуйста проверьте свою почту чтобы завершить регистрацию</h2>
</div>
{% endblock %}

eleng/users/templates/users/custom_clearable_file_input.html
{% if is_initial %}
    <input type="file" name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>
{% endif %}

eleng/users/templates/users/invalid_verify.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2 class="users-h2">Ваша ссылка не корректна, залогиньтесь снова</h2>
    <a href="{% url 'users:login' %}">ВОЙТИ</a>
</div>
{% endblock %}

eleng/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2 class="users-h2">Авторизация</h2>

    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}"/>

        {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div class="message {{ message.tags }}">{{ message }}</div>
                {% endfor %}
            </div>
        {% endif %}

        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
            <p>
                <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>
                {% if f.field.widget.input_type == 'password' %}
                    <div style="position: relative;">
                        {{ f }}
                        <button type="button" onclick="togglePasswordVisibility('{{ f.id_for_label }}');" style="position: absolute; right: 10px; top: 10px; border: none; background: none; cursor: pointer;">
                            <i id="toggleEye{{ f.id_for_label }}" class="fas fa-eye"></i>
                        </button>
                    </div>
                {% else %}
                    {{ f }}
                {% endif %}
                <div class="form-error">{{ f.errors }}</div>
            </p>
        {% endfor %}
        <div class="social">
            <ul>
                <li>
                    <button type="submit">Войти</button>
                </li>
                <li class="google">
                    <a href="{% url 'social:begin' 'google-oauth2' %}">
                        Sign in with Google
                    </a>
                </li>
            </ul>
        </div>
        <div class="forgot-password">
            <a href="{% url 'users:password_reset' %}">Забыли пароль?</a>
        </div>
        
    </form>
</div>

<script>
    function togglePasswordVisibility(fieldId) {
        var passwordInput = document.getElementById(fieldId);
        var toggleIcon = document.getElementById('toggleEye' + fieldId);
        if (passwordInput.type === 'password') {
            passwordInput.type = 'text';
            toggleIcon.classList.remove('fa-eye');
            toggleIcon.classList.add('fa-eye-slash');
        } else {
            passwordInput.type = 'password';
            toggleIcon.classList.remove('fa-eye-slash');
            toggleIcon.classList.add('fa-eye');
        }
    }
</script>
{% endblock %}

eleng/users/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2 class="users-h2">Изменение пароля</h2>

    <form method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <p><button type="submit">Изменить пароль</button></p>
    </form>
</div>
{% endblock %}

eleng/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h2 class="users-h2">Пароль изменен</h2>

        <p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
            <a href="{% url 'users:login' %}"><span style="color: blue;">входа в систему</span></a>
        </p>
    </div>
    
    
{% endblock %}

eleng/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2 class="users-h2">Новый пароль</h2>

    <form method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <p><button type="submit">Сохранить</button></p>
    </form>
</div>
{% endblock %}

eleng/users/templates/users/password_reset_done.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
<div class="container">
    <h2 class="users-h2">Сброс пароля</h2>

    <p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

    <p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
</div>
{% endblock %}

eleng/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

eleng/users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2 class="users-h2">Восстановление пароля</h2>

    <form method="post">
        {% csrf_token %}
        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <p><button type="submit">Сбросить по E-mail</button></p>
    </form>
</div>
{% endblock %}

eleng/users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2 class="users-h2">Профиль</h2>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="avatar-wrapper">
            <img src="{{ user.avatar.url }}" width="80px" height="80px" id="avatar-image">
            <input type="file" name="avatar" id="avatar-input" style="display: none;">
        </div>
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
            {% if f.name != 'avatar' %}
                <p>
                    <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>
                    {{ f }}
                </p>
                <div class="form-error">{{ f.errors }}</div>
            {% endif %}
        {% endfor %}

        <p><button type="submit">Сохранить</button></p>

        {% if user.has_usable_password %}
            <div class="password-change-link">
                <a href="{% url 'users:password_change' %}">Сменить пароль</a>
            </div>
        {% endif %}
    </form>

</div>

<script>
    document.getElementById('avatar-input').addEventListener('change', function(event) {
        if (event.target.files && event.target.files[0]) {
            var reader = new FileReader();
            reader.onload = function(e) {
                document.getElementById('avatar-image').src = e.target.result;
            }
            reader.readAsDataURL(event.target.files[0]);
        }
    });

    document.getElementById('avatar-image').addEventListener('click', function() {
        document.getElementById('avatar-input').click();
    });
</script>

{% endblock %}

eleng/users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2 class="users-h2">Регистрация</h2>
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
            <p>
                <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>
                {% if f.name == 'password1' or f.name == 'password2' %}
                    <div style="position: relative;">
                        {{ f }}
                        <button type="button" onclick="togglePasswordVisibility('{{ f.id_for_label }}');" style="position: absolute; right: 10px; top: 10px; border: none; background: none;">
                            <i id="toggleEye{{ f.id_for_label }}" class="fas fa-eye"></i>
                        </button>
                    </div>
                {% else %}
                    {{ f }}
                {% endif %}
                <div class="form-error">{{ f.errors }}</div>
            </p>
        {% endfor %}
        <p><button type="submit">Регистрация</button></p>
    </form>
</div>

<script>
    function togglePasswordVisibility(fieldId) {
        var passwordInput = document.getElementById(fieldId);
        var toggleIcon = document.getElementById('toggleEye' + fieldId);
        if (passwordInput.type === 'password') {
            passwordInput.type = 'text';
            toggleIcon.classList.remove('fa-eye');
            toggleIcon.classList.add('fa-eye-slash');
        } else {
            passwordInput.type = 'password';
            toggleIcon.classList.remove('fa-eye-slash');
            toggleIcon.classList.add('fa-eye');
        }
    }
</script>

{% endblock %}

eleng/users/templates/users/register_done.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2 class="users-h2">Добро пожаловать!</h2>
    <p>Вы успешно зарегистрировались на сайте! Для входа в систему необходимо авторизоваться по этой
    <a href="{% url 'users:login' %}">ссылке</a></p>
</div>
{% endblock %}

eleng/users/templates/users/verify_email.html
{% autoescape off %}

Hi {{ user.get_username }},
Пожалуйста перейдите по ссылке чтобы закончить регистрацию
http://{{ domain }}{% url 'users:verify_email' uidb64=uid token=token %}

{% endautoescape %}